### ISSUE TITLE
About Alphafold-Swiss-Prot Dataset download

### ISSUE THREAD

**Issue by AI4S-Ritsuka** [mrzzmrzz/SCOP#1]
Thanks for your work. I have a question about the dataset. The AlphaFold-Swiss-Prot dataset is around 27GB, and the download speed from the original website is quite slow. Could you provide any domestic mirrors for the dataset?

**Comment by mrzzmrzz** [comment]
Thank you for your kind word! To the best of my knowledge, users accessing https://alphafold.ebi.ac.uk/download from the China Education Network (CERNET) should generally experience download speeds of around 5MB/s, with variations depending on your network. If your connection is faster, the download should be even quicker.

Unfortunately, as I have already graduated, I no longer have access to the resources on the lab's cluster and thus cannot share my processed files with you. By the way, I remember the processed files were quite large, and sharing them directly would be a bit troublesome. I still recommend obtaining these files by processing PDB files.

However, please feel free to reach out if you have any other questions—I’d be more than happy to discuss them with you!
